# Generated by Django 4.2.11 on 2024-03-05 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=123)),
                ('username', models.CharField(max_length=123, null=True)),
                ('tg_id', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=123)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_admin', to='api.admingroup')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=123)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_admin', to='api.admingroup')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_positions', to='api.group')),
            ],
        ),
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.CharField(max_length=15)),
                ('first_name', models.CharField(max_length=123)),
                ('last_name', models.CharField(max_length=123)),
                ('username', models.CharField(max_length=123, null=True)),
                ('birthday', models.DateField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_users_admin', to='api.admingroup')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_users_group', to='api.group')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_users_position', to='api.position')),
            ],
        ),
    ]
